USE master;
GO

IF DB_ID('Reckitt_Sales_Analysis') IS NOT NULL
BEGIN
    ALTER DATABASE Reckitt_Sales_Analysis 
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Reckitt_Sales_Analysis;
END
GO

CREATE DATABASE Reckitt_Sales_Analysis;
GO

USE Reckitt_Sales_Analysis;
GO

-- =============================================
-- 1. DIMENSIONES
-- =============================================

CREATE TABLE DIM_CATEGORY (
    ID_CATEGORY NVARCHAR(50),
    CATEGORY NVARCHAR(200)
);

CREATE TABLE DIM_SEGMENT (
    CATEGORY NVARCHAR(100),
    ATTR1 NVARCHAR(100),
    ATTR2 NVARCHAR(100),
    ATTR3 NVARCHAR(100),
    FORMAT NVARCHAR(50),
    SEGMENT NVARCHAR(150)
);

CREATE TABLE DIM_PRODUCT (
    MANUFACTURER NVARCHAR(100),
    BRAND NVARCHAR(100),
    ITEM NVARCHAR(50),
    ITEM_DESCRIPTION NVARCHAR(300),
    CATEGORY NVARCHAR(100),
    FORMAT NVARCHAR(50),
    ATTR1 NVARCHAR(100),
    ATTR2 NVARCHAR(100),
    ATTR3 NVARCHAR(100)
);

CREATE TABLE DIM_CALENDAR (
    WEEK NVARCHAR(50),
    YEAR NVARCHAR(50),
    MONTH NVARCHAR(50),
    WEEK_NUMBER NVARCHAR(50),
    DATE_VALUE NVARCHAR(50)
);
GO

PRINT 'DIMENSIONS CREATED';
GO

-- =============================================
-- 2. FACT RAW
-- =============================================

CREATE TABLE FACT_SALES_RAW (
    WEEK NVARCHAR(50),
    ITEM_CODE NVARCHAR(50),
    TOTAL_UNIT_SALES NVARCHAR(50),
    TOTAL_VALUE_SALES NVARCHAR(50),
    TOTAL_UNIT_AVG_WEEKLY_SALES NVARCHAR(50),
    REGION NVARCHAR(100)
);
GO

PRINT 'RAW TABLE CREATED';
GO

-- =============================================
-- 3. LOAD DATA
-- =============================================

BULK INSERT DIM_CATEGORY
FROM 'D:\Documentos\Ebac\Finales\entregable_4\data\DIM_CATEGORY.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT DIM_SEGMENT
FROM 'D:\Documentos\Ebac\Finales\entregable_4\data\DIM_SEGMENT.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT DIM_PRODUCT
FROM 'D:\Documentos\Ebac\Finales\entregable_4\data\DIM_PRODUCT.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT DIM_CALENDAR
FROM 'D:\Documentos\Ebac\Finales\entregable_4\data\DIM_CALENDAR.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');

BULK INSERT FACT_SALES_RAW
FROM 'D:\Documentos\Ebac\Finales\entregable_4\data\FACT_SALES.csv'
WITH (FIRSTROW=2, FIELDTERMINATOR=',', ROWTERMINATOR='0x0a', CODEPAGE='65001');
GO

PRINT 'DATA LOADED';
GO

-- =============================================
-- 4. CLEAN LAYER
-- =============================================

DROP TABLE IF EXISTS FACT_SALES;
GO

SELECT
    LTRIM(RTRIM(WEEK)) AS WEEK,

    REPLACE(REPLACE(LTRIM(RTRIM(ITEM_CODE)),'"',''),' ','') AS ITEM_CODE,

    TRY_CONVERT(FLOAT, REPLACE(REPLACE(TOTAL_UNIT_SALES,'"',''),',','')) AS TOTAL_UNIT_SALES,
    TRY_CONVERT(FLOAT, REPLACE(REPLACE(TOTAL_VALUE_SALES,'"',''),',','')) AS TOTAL_VALUE_SALES,
    TRY_CONVERT(FLOAT, REPLACE(REPLACE(TOTAL_UNIT_AVG_WEEKLY_SALES,'"',''),',','')) AS AVG_WEEKLY_SALES,

    LTRIM(RTRIM(REGION)) AS REGION
INTO FACT_SALES
FROM FACT_SALES_RAW;
GO

PRINT 'CLEAN FACT CREATED';
GO

-- =============================================
-- 5. VALIDACIÓN
-- =============================================

SELECT 'RAW' AS TYPE, COUNT(*) AS ROWS FROM FACT_SALES_RAW
UNION ALL
SELECT 'CLEAN', COUNT(*) FROM FACT_SALES;
GO

-- =============================================
-- 6. DATA QUALITY CHECK
-- =============================================

-- NULOS
SELECT 
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN TOTAL_VALUE_SALES IS NULL THEN 1 ELSE 0 END) AS NULL_VALUES
FROM FACT_SALES;
GO

-- MATCH DE JOIN
SELECT 
    COUNT(*) AS MATCHED_ROWS
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON REPLACE(f.ITEM_CODE,'"','') = REPLACE(p.ITEM,'"','');
GO

-- NO MATCH
SELECT COUNT(*) AS UNMATCHED_ROWS
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
    ON REPLACE(f.ITEM_CODE,'"','') = REPLACE(p.ITEM,'"','')
WHERE p.ITEM IS NULL;
GO

-- =============================================
-- 7. ANALYTICS
-- =============================================

-- VENTAS POR REGIÓN
SELECT 
    REGION,
    SUM(TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;
GO

-- TOP PRODUCTOS
SELECT TOP 5
    ITEM_CODE,
    SUM(TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY ITEM_CODE
ORDER BY TOTAL_SALES DESC;
GO

-- VENTAS POR CATEGORÍA
SELECT 
    c.CATEGORY AS CATEGORY_NAME,
    SUM(f.TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON REPLACE(f.ITEM_CODE,'"','') = REPLACE(p.ITEM,'"','')
JOIN DIM_CATEGORY c
    ON p.CATEGORY = c.ID_CATEGORY
GROUP BY c.CATEGORY
ORDER BY TOTAL_SALES DESC;
GO

-- =============================================
-- 8. ANÁLISIS TEMPORAL
-- =============================================

SELECT 
    WEEK,
    SUM(TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY WEEK
ORDER BY WEEK;
GO

SELECT TOP 1
    WEEK,
    SUM(TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES
GROUP BY WEEK
ORDER BY TOTAL_SALES DESC;
GO

-- =============================================
-- 9. KPI
-- =============================================

-- PRECIO PROMEDIO
SELECT 
    SUM(TOTAL_VALUE_SALES) / NULLIF(SUM(TOTAL_UNIT_SALES),0) AS AVG_PRICE
FROM FACT_SALES;
GO

-- PRECIO POR PRODUCTO
SELECT TOP 10
    ITEM_CODE,
    SUM(TOTAL_VALUE_SALES) / NULLIF(SUM(TOTAL_UNIT_SALES),0) AS PRICE_PER_UNIT
FROM FACT_SALES
GROUP BY ITEM_CODE
ORDER BY PRICE_PER_UNIT DESC;
GO

-- =============================================
-- 10. VISTA ANALÍTICA
-- =============================================

CREATE OR ALTER VIEW VW_SALES_ANALYSIS AS
SELECT 
    f.WEEK,
    f.REGION,
    p.BRAND,
    c.CATEGORY,
    f.TOTAL_VALUE_SALES,
    f.TOTAL_UNIT_SALES
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON REPLACE(f.ITEM_CODE,'"','') = REPLACE(p.ITEM,'"','')
JOIN DIM_CATEGORY c
    ON p.CATEGORY = c.ID_CATEGORY;
GO

-- USO DE LA VISTA
SELECT 
    CATEGORY,
    SUM(TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM VW_SALES_ANALYSIS
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;
GO

-- =============================================
-- SALES BY CATEGORY NAME
-- =============================================

SELECT 
    c.CATEGORY AS CATEGORY_NAME,
    SUM(f.TOTAL_VALUE_SALES) AS TOTAL_SALES
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.ITEM_CODE = REPLACE(p.ITEM,'"','')
JOIN DIM_CATEGORY c
    ON p.CATEGORY = c.ID_CATEGORY
GROUP BY c.CATEGORY
ORDER BY TOTAL_SALES DESC;
GO

CREATE INDEX IDX_FACT_ITEM ON FACT_SALES(ITEM_CODE);
CREATE INDEX IDX_FACT_REGION ON FACT_SALES(REGION);
CREATE INDEX IDX_PRODUCT_ITEM ON DIM_PRODUCT(ITEM);
GO

-- =============================================
-- 11. BUSINESS INSIGHT
-- =============================================

SELECT 
    c.CATEGORY AS CATEGORY_NAME,
    f.REGION,
    SUM(f.TOTAL_VALUE_SALES) AS SALES,
    SUM(f.TOTAL_UNIT_SALES) AS UNITS,
    SUM(f.TOTAL_VALUE_SALES) / NULLIF(SUM(f.TOTAL_UNIT_SALES),0) AS PRICE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.ITEM_CODE = REPLACE(p.ITEM,'"','')
JOIN DIM_CATEGORY c
    ON p.CATEGORY = c.ID_CATEGORY
GROUP BY c.CATEGORY, f.REGION
ORDER BY SALES DESC;
GO