USE master;
GO

IF DB_ID('EntregaFinalSQL') IS NOT NULL
BEGIN
    ALTER DATABASE EntregaFinalSQL SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE EntregaFinalSQL;
END
GO

CREATE DATABASE EntregaFinalSQL
ON PRIMARY
(
    NAME = EntregaFinalSQL,
    FILENAME = 'D:\Documentos\Ebac\Finales\EntregaFinal\EntregaFinalSQL.mdf',
    SIZE = 50MB,
    MAXSIZE = 500MB,
    FILEGROWTH = 10MB
)
LOG ON
(
    NAME = EntregaFinalSQL_log,
    FILENAME = 'D:\Documentos\Ebac\Finales\EntregaFinal\EntregaFinalSQL_log.ldf',
    SIZE = 20MB,
    MAXSIZE = 200MB,
    FILEGROWTH = 10MB
);
GO

USE EntregaFinalSQL;
GO
-------------------------------------------
CREATE TABLE DIM_CATEGORY (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NULL
);
GO

CREATE TABLE DIM_SEGMENT (
    SEGMENT_ID INT PRIMARY KEY,
    SEGMENT_NAME VARCHAR(100) NULL
);
GO

CREATE TABLE DIM_CALENDAR (
    WEEK INT PRIMARY KEY,
    YEAR INT NULL,
    MONTH INT NULL,
    MONTH_NAME VARCHAR(20) NULL,
    QUARTER INT NULL
);
GO

CREATE TABLE DIM_PRODUCT (
    ITEM VARCHAR(20) PRIMARY KEY,
    MANUFACTURER VARCHAR(100) NULL,
    BRAND VARCHAR(100) NULL,
    ITEM_DESCRIPTION VARCHAR(500) NULL,
    CATEGORY INT NULL,
    SEGMENT INT NULL,
    FORMAT VARCHAR(100) NULL,
    ATTR1 VARCHAR(100) NULL,
    ATTR2 VARCHAR(100) NULL,
    ATTR3 VARCHAR(100) NULL
);
GO

CREATE TABLE FACT_SALES (
    WEEK INT NOT NULL,
    ITEM_CODE VARCHAR(20) NOT NULL,
    TOTAL_UNIT_SALES FLOAT NULL,
    TOTAL_VALUE_SALES FLOAT NULL,
    TOTAL_UNIT_AVG_WEEKLY_SALES FLOAT NULL,
    REGION VARCHAR(100) NULL
);
GO
-------------------------------------
SELECT TOP 10 * FROM DIM_PRODUCT;